### ISSUE TITLE
 Taskwiki on vim with python3

### ISSUE THREAD

**Issue by Futurile** [tbabej/taskwiki#111]
I saw that in #108 there was a merge to work with Python3, this is just confirming 'working so far' on Ubuntu 16.04 with Python3 by default for vim.

Vim version:
```
  $ vim --version
  shows +python3 -python
 ```
This is what I've done so far:

a. Installed Vimwiki
In my vimrc I have: 
```
NeoBundle 'vimwiki/vimwiki', {'branch' : 'dev', 'rev' : '3a87437'}
```
b. Install pip3
```
  $ sudo apt install python3-pip
```
b. Installed Tasklib
```
  $ pip3 install --user git+git://github.com/tbabej/tasklib@develop
```
c. Installed Taskwiki
In .vimrc I have:
```
NeoBundle 'tbabej/taskwiki'
```
d. In Vim vimwiki and taskwiki load
I can do

```
:TaskWikiProjects
:TaskWikiTags
:TaskWikiMod
Vimwiki commands e.g. VimwikiToggleListItem and saving are reflected in Taskwarrior
```

So far so good I think.

**Comment by tbabej** [comment]
Thanks for letting me know, much appreciated.

I also setup Travis CI to test on python3 too, but automation has some problems I couldn't track down yet, so it's good to know it's working fine on actual Ubuntu system.

**Comment by Futurile** [comment]
@tbabej 

I built a docker image today and filter is definitely not working with my set-up. Would you mind grabbing it and having a look at what I'm doing wrong?

My set-up is:

Ubuntu 16.04
Vim 8.0
Taskwarrior 2.5.0

It's a big image but has some example task data with vimwiki and a minimal wiki page to show the filtering issue I see. You can grab it from here:

  docker pull futurile/2017010301-ubuntu-taskwiki

Thanks!

**Comment by tbabej** [comment]
Thanks for the setup! This turned out to be a python3 port issue, fixed in master.

**Comment by Futurile** [comment]
With the last change python3 works, but you now can't view tasks without a filter with python2 or python3. I'm only showing the Python3 containers error here.

There appears to be a separate issue around vim 8.0 (I will open a separate issue).

```
Version: Task 2.4, Vim7.4, Python 3.5.2
Container name     taskwiki-vim7-python3            
Taskwiki list all [1]                            No      
View +MONTH                                      Yes          
View project                                     Yes   
Add a task in all tasks                          TBD         
Add a task under a filter (+MONTH)               Yes         
Add a task under project                         Yes          
Add a sub-task on project                        Yes  
Modify a task  (TaskWikiMod)                     Yes        
```

1. Taskwiki list all
Actions performed:
  * Go to the main page (\ww)
  * Add a filter to see all tasks
            == All tasks view | ==

Expected outcome:
  All tasks are shown

Actual output:

```
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/root/.vim/bundle/taskwiki/taskwiki/main.py", line 56, in update_to_tw
    cache.evaluate_viewports()
  File "/root/.vim/bundle/taskwiki/taskwiki/cache.py", line 171, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 297, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 271, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 249, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/root/.local/lib/python3.5/site-packages/tasklib/task.py", line 474, in __iter__
    self._result_cache = self._execute()
  File "/root/.local/lib/python3.5/site-packages/tasklib/task.py", line 506, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/root/.local/lib/python3.5/site-packages/tasklib/backends.py", line 309, in filter_tasks
    for line in self.execute_command(args):
  File "/root/.local/lib/python3.5/site-packages/tasklib/backends.py", line 276, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: Using alternate .taskrc file /root/.taskrc
Configuration override rc.context:
Configuration override rc.recurrence.confirmation:no
Configuration override rc.bulk:0
Configuration override rc.dependency.confirmation:no
Configuration override rc.confirmation:no
Configuration override rc.json.array:off
```

**Comment by tbabej** [comment]
If this is happening both on Python2 and Python3, let's create a separate issue. Let's keep this thread only for python3 incompatibilities.

**Comment by tbabej** [comment]
Reference for the empty filter issue: #112

**Comment by Futurile** [comment]
```
Python 3.5.2; Vim 7.4; Taskwarrior 2.5.0
---------------------------------------------------
Taskwiki commit:                      f2c9324
Container name                        taskwiki-vim7-python3
Taskwiki list all                     Yes
View +MONTH                           Yes
View project                          Yes
Add a task in 'all tasks':            Yes
Add a task, filter, explicit syntax:  Yes
Add a task under a project:           Yes
Add a sub-task under a project:       Yes
Modify a task (TaskWikiMod):          Yes
View information on a task:           Yes
Attach an annotation:                 Yes
Mark a task as done (TaskWikiDone):   Yes

```

**Comment by tbabej** [comment]
Thanks for the extensive testing!

In case you would be interested into contributing some automated tests, I recommend you having a look into our test suite - some of it is [pretty declarative](https://github.com/tbabej/taskwiki/blob/master/tests/test_viewport.py).
