### ISSUE TITLE
Empty viewport filter raises error

### ISSUE THREAD

**Issue by tbabej** [tbabej/taskwiki#112]
As reported by Futurile, a viewport without a filter:

    === Name | ===

results into a error:

```
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/root/.vim/bundle/taskwiki/taskwiki/main.py", line 56, in update_to_tw
    cache.evaluate_viewports()
  File "/root/.vim/bundle/taskwiki/taskwiki/cache.py", line 171, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 297, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 271, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 249, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/root/.local/lib/python3.5/site-packages/tasklib/task.py", line 474, in __iter__
    self._result_cache = self._execute()
  File "/root/.local/lib/python3.5/site-packages/tasklib/task.py", line 506, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/root/.local/lib/python3.5/site-packages/tasklib/backends.py", line 309, in filter_tasks
    for line in self.execute_command(args):
  File "/root/.local/lib/python3.5/site-packages/tasklib/backends.py", line 276, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: Using alternate .taskrc file /root/.taskrc
Configuration override rc.context:
Configuration override rc.recurrence.confirmation:no
Configuration override rc.bulk:0
Configuration override rc.dependency.confirmation:no
Configuration override rc.confirmation:no
Configuration override rc.json.array:off
```

We should either ignore such viewports, or display all tasks.

**Comment by tbabej** [comment]
Fixed in master, covered by tests.
