### ISSUE TITLE
Support for accentuation in projects

### ISSUE THREAD

**Issue by MartyLake** [tbabej/taskwiki#115]
`== à faire | Reunion2017 ==` is ok

but `== à faire | Réunion2017 ==` yield this error :

```
Erreur détectée en traitant Autocommandes BufWrite pour "*.wiki" :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/d/Unsaved/Dropbox/Vimrc/.vim/bundle/taskwiki/taskwiki/main.py", line 54, in update_to_tw
    cache.evaluate_viewports()
  File "/mnt/d/Unsaved/Dropbox/Vimrc/.vim/bundle/taskwiki/taskwiki/cache.py", line 172, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/mnt/d/Unsaved/Dropbox/Vimrc/.vim/bundle/taskwiki/taskwiki/viewport.py", line 297, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/mnt/d/Unsaved/Dropbox/Vimrc/.vim/bundle/taskwiki/taskwiki/viewport.py", line 271, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/mnt/d/Unsaved/Dropbox/Vimrc/.vim/bundle/taskwiki/taskwiki/viewport.py", line 249, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/usr/local/lib/python2.7/dist-packages/tasklib/task.py", line 474, in __iter__
    self._result_cache = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/tasklib/task.py", line 506, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/usr/local/lib/python2.7/dist-packages/tasklib/backends.py", line 309, in filter_tasks
    for line in self.execute_command(args):
  File "/usr/local/lib/python2.7/dist-packages/tasklib/backends.py", line 266, in execute_command
    args, config_override=config_override)
  File "/usr/local/lib/python2.7/dist-packages/tasklib/backends.py", line 135, in _get_command_args
    command_args.extend(map(six.text_type, args))
"Réunion2017.wiki" 22L, 258C écrit(s)
Appuyez sur ENTRÉE ou tapez une commande pour continuer
```

**Comment by tbabej** [comment]
Unicode characters are now supported in viewports, also during split selection of tags and projects. All of this is covered by tests and was pushed to master.
