### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by tjfwalker** [tbabej/taskwiki#134]
Upon launching vimwiki via `<Leader>ww`:
```
Error detected while processing function provider#python3#Call:                                                                                   
line   18:                                                                                                                                        
Traceback (most recent call last):                                                                                                                
  File "/Users/tj/.vim/plugged/taskwiki/taskwiki/main.py", line 6, in <module>                                                                    
    import six                                                                                                                                    
ModuleNotFoundError: No module named 'six'                                                                                                        
Traceback (most recent call last):                                                                                                                
  File "<string>", line 1, in <module>                                                                                                            
NameError: name 'cache' is not defined
```
...then, nothing works. Similar errors upon attempting to follow [Wikilinks](https://github.com/vimwiki/vimwiki/blob/dev/doc/vimwiki.txt#L815).

**Comment by tbabej** [comment]
Try installing tasklib for python3:

    sudo pip3 install --upgrade git+git://github.com/tbabej/tasklib@develop

**Comment by tjfwalker** [comment]
```
❯ sudo pip3 install --upgrade git+git://github.com/tbabej/tasklib@develop
The directory '/Users/tj/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/tj/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+git://github.com/tbabej/tasklib@develop
  Cloning git://github.com/tbabej/tasklib (to develop) to /private/tmp/pip-sxsr_wng-build
Requirement already up-to-date: six>=1.4 in ./.pyenv/versions/3.6.0/lib/python3.6/site-packages (from tasklib==1.0.0)
Requirement already up-to-date: pytz in ./.pyenv/versions/3.6.0/lib/python3.6/site-packages (from tasklib==1.0.0)
Requirement already up-to-date: tzlocal in ./.pyenv/versions/3.6.0/lib/python3.6/site-packages (from tasklib==1.0.0)
Installing collected packages: tasklib
  Found existing installation: tasklib 1.0.0
    Uninstalling tasklib-1.0.0:
      Successfully uninstalled tasklib-1.0.0
  Running setup.py install for tasklib ... done
Successfully installed tasklib-1.0.0
```

However, this seems to have had no effect. I'm still getting the above-descrived error.

**Comment by tjfwalker** [comment]
I _do_ see that error about dir ownership and cache being disabled. I don't know what to make of that, though. Is it relevant?

**Comment by jvmCarneiro** [comment]
What distro are you running? I've had that same problem using Arch Linux, before I started getting [this instead](https://github.com/tbabej/taskwiki/issues/133). 

Now, I'm not really sure of my steps between one issue and another, but I believe I installed python2-pip and reinstalled tasklib with it, and later installed python-tasklib from the aur. Which worked, if any, I don't really know. I already had python-pip (python 3 in arch) previously installed.
 
Also, did you install vimwiki through its dev branch?

**Comment by tjfwalker** [comment]
@jvmCarneiro, I'm on macOS Sierra (10.12.3).

So, try with pip2?

I did install [vimwiki](https://github.com/vimwiki/vimwiki)'s dev branch —via [vim-plug](https://github.com/junegunn/vim-plug): `Plug 'vimwiki/vimwiki', { 'branch': 'dev' }`

**Comment by tbabej** [comment]
@tjfwalker You can try with pip2, but it seems that your vim is using python3 (which is the default now, if available). Can you provide full error message?

**Comment by tbabej** [comment]
I had a second look and now I see where your problem is. When you use pip, you actually do not install to system-wide site packages, but to ~/.pyenv/, qouting from your pip output:

    ./.pyenv/versions/3.6.0/lib/python3.6/site-packages

this is a result of using `pyenv` (usually done to allow multiple versions of python living side by side). Seems that vim does not respect your pyenv settings and you need to install python packages globally, which would mean circumventing pyenv by specifying the pip3 tool directly:

    sudo /usr/bin/pip3 install tasklib

**Comment by jvmCarneiro** [comment]
Makes sense, that's probably why installing it from the repo solved it on my side.

**Comment by tjfwalker** [comment]
I've got the following in my `init.vim` and thought it was supposed to address what you've mentioned, @tbabej,  regarding the python location —as managed by `pyenv virtualenv`— and `(n)vim` finding it. Have I misunderstood?

~/.config/nvim/init.vim
```
let g:python_host_prog = '/Users/tj/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/Users/tj/.pyenv/versions/neovim3/bin/python'
```

**Comment by tjfwalker** [comment]
Here's the output I get for `:CheckHealth` from ex mode (which I took to mean that (n)vim is finding python fine):

```
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

## Configuration
  - SUCCESS: no issues found

## Performance

NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170320-29597-1od6tt7/neovim-0.1.7/build/config -I/tmp/neovim-20170320-29597-1od6tt7/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170320-29597-1od6tt7/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170320-29597-1od6tt7/neovim-0.1.7/build/include
Compiled by tj@TJs-MacBook-Pro.lan

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"

  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,


## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: Using: g:python_host_prog = "/Users/tj/.pyenv/versions/neovim2/bin/python"
  - INFO: Executable: /Users/tj/.pyenv/versions/neovim2/bin/python
  - INFO: Python2 version: 2.7.13
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/Users/tj/.pyenv/versions/neovim3/bin/python"
  - INFO: Executable: /Users/tj/.pyenv/versions/neovim3/bin/python
  - INFO: Python3 version: 3.6.0
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

**Comment by tbabej** [comment]
With neovim, taskwiki will prefer python3. That means you need to get the following to work:

    $ /Users/tj/.pyenv/versions/neovim3/bin/python
    >>> import tasklib

**Comment by tjfwalker** [comment]
Success. I needed to:
```
$ pyenv activate neovim3
(neovim3) $ pip3 install --upgrade git+git://github.com/tbabej/tasklib@develop
$ /Users/tj/.pyenv/versions/neovim3/bin/python
>>> import tasklib
```

Thanks

**Comment by tbabej** [comment]
Way to go! Nice to see you figured it out. Reach out if you have any problems with the taskwiki itself.
