### ISSUE TITLE
Multiple tabs breaks link following

### ISSUE THREAD

**Issue by sophacles** [tbabej/taskwiki#158]
I'm seeing a strange issue with multiple tabs. When I have 2 tabs open to the same wiki (different pages or the same page) and I press enter to follow a link, i get this error:

```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/eheine/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/Users/eheine/.vim/bundle/taskwiki/taskwiki/main.py", line 290, in task_info_or_vimwiki_follow_link
    vim.command('VimwikiFollowLink')
vim.error: Vim(let):E684: list index out of range: 2
```

When taskwiki is off, I can brows the wiki in multiple tabs with no issue.

Some addition information that may be helpful:
* vim version:
   ```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 22 2017 07:10:35)
MacOS X (unix) version
Included patches: 1-648
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     +tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminfo
+browse          +fork()          +multi_lang      +termresponse
++builtin_terms  +fullscreen      -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +odbeditor       +toolbar
+clientserver    +insert_expand   +packages        +transparency
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
+file_in_path    +mouse_sgr       +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/opt/python/Frameworks -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/opt/python/Frameworks -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -oVim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/opt/python/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```
* Vimwiki syntax: markdown

If more info is needed I'll gladly provide it.

**Comment by tbabej** [comment]
This seems to be a vimwiki problem - is this issue present when taskwiki is completely blocked out? (i.e. removed from `~/.vim/bundle`).

**Comment by sophacles** [comment]
It stops happening when i remove taskwiki from `~/.vim/bundle`. It also stops happening when taskwiki is present in that dir but i comment out the line `Plug 'tbabej/taskwiki'` in my vimrc.

I should note that this vimwiki is using markdown syntax in the config. Don't know if that matters, but specifically it is set up as:

```
let g:vimwiki_list = [{'path': '~/resources/Documents/wiki', 'ext': '.md',
                      \ 'syntax': 'markdown', "nested_syntaxes": {'python': 'python'}}]
```

**Comment by tbabej** [comment]
What happes if, with taskwiki disabled, you have cursor on the link and type out the `:VimwikiFollowLink` command manually?

I suppose this should still work in your case, but it's better to verify. Alll we do is just running that command, as is apparent from the traceback in the original probelm description.

**Comment by sophacles** [comment]
Confirmed - Same results as described above:

* with vimwiki and taskwiki installed and enabled: error
* with vimwiki installed and taskwiki installed but disabled: no error
* with vimwiki installed and taskwiki not installed: no error
