### ISSUE TITLE
Cannot handle latin1 characters

### ISSUE THREAD

**Issue by mowgli** [tbabej/taskwiki#163]
I have many tasks with latin1 characters (like ä, ö or ü). And all my encoding is latin1, also in vim.

That is no problem with vim, shell or task, but taskwiki seems to break with that:
```
Fehler beim Ausführen von "BufWrite Autokommandos für "*.wiki"":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/main.py", line 60, in update_to_tw
    c.evaluate_viewports()
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/cache.py", line 216, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/viewport.py", line 325, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/viewport.py", line 299, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/home/klaus/.vim/bundle/taskwiki/taskwiki/viewport.py", line 277, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/usr/lib/python3/dist-packages/tasklib/task.py", line 474, in __iter__
    self._result_cache = self._execute()
  File "/usr/lib/python3/dist-packages/tasklib/task.py", line 506, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/usr/lib/python3/dist-packages/tasklib/backends.py", line 314, in filter_tasks
    for line in self.execute_command(args):
  File "/usr/lib/python3/dist-packages/tasklib/backends.py", line 274, in execute_command
    stdout, stderr = [x.decode('utf-8') for x in p.communicate()]
  File "/usr/lib/python3/dist-packages/tasklib/backends.py", line 274, in <listcomp>
    stdout, stderr = [x.decode('utf-8') for x in p.communicate()]
```
… when writing a file with a header that filters some tasks.

**Comment by mowgli** [comment]
Froget that, it is a bug in tasklib and I did already a pull request that fixes it.
