### ISSUE TITLE
VimwikiFollowLink

### ISSUE THREAD

**Issue by rolandog** [tbabej/taskwiki#173]

**Comment by rolandog** [comment]
A bit out of desperation, I hit `<CR>` twice, and I received the following (different) error message:

```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rolandog/.vim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/rolandog/.vim/plugged/taskwiki/taskwiki/main.py", line 275, in task_info_or_vimwiki_follow_link
    vim.command('VimwikiFollowLink')
vim.error: Vim(edit):E325: ATTENTION
```

Upon hitting `<CR>` again, I was presented with the file in read-only mode.

After researching, I found a similar issue in #94 . And indeed, I had a swap file present.

I then followed [this superuser.com answer](https://superuser.com/questions/218262/how-to-get-rid-of-the-warnings-when-opening-a-file-that-has-a-swp-file/498658#498658) and after confirming that the files were identical, removed the `swp` file.

This fixed my problem.

So, I'm guessing the root cause would be that there is no way to handle the presence of `swp` files in Taskwiki.

**Comment by rolandog** [comment]
After I started getting a somewhat similar error, I revisited this issue;  after searching for a swap file:
``` shell
find ~ -type f -name "*.swp"
```
I found no swap files.

I remembered to update and, after updating via `:PlugUpdate` (and reading through the commits), I found that a [similar issue](https://github.com/vimwiki/vimwiki/issues/540#issuecomment-409600685) was detected and [patched by Nudin](https://github.com/vimwiki/vimwiki/commit/2185815b0004018cc4c5261f7be1d6936c9fcd22).

However, I think I should file the error I mentioned at the beginning of the comment as a different issue.

**Comment by jakobkolb** [comment]
I am having the exact same Issue.
