### ISSUE TITLE
ImportError: No module named 'tasklib'

### ISSUE THREAD

**Issue by mrbig033** [tbabej/taskwiki#178]
* MX Linux 17
* NVIM v0.3.0-1029-g48967695c, Build type: RelWithDebInfo
* [init.vim](https://gitlab.com/mrbig/dotfiles/blob/master/nvim/init.vim)
* [pluggins.vim](https://gitlab.com/mrbig/dotfiles/blob/master/nvim/plugins.vim)
* [complete environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

I installed tasklib according to the instructions, but I had to use the "-H" option for it to work:
`sudo -H pip install --upgrade git+git://github.com/tbabej/tasklib@develop`. And now I'm getting this message:
```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "$nvim/plugins/plugged/taskwiki/taskwiki/main.py", line 15, in <module>
    from taskwiki import cache as cache_module
  File "$nvim/plugins/plugged/taskwiki/taskwiki/cache.py", line 5, in <module>
    from taskwiki import viewport
  File "$nvim/plugins/plugged/taskwiki/taskwiki/viewport.py", line 6, in <module>
    from taskwiki import vwtask
  File "$nvim/plugins/plugged/taskwiki/taskwiki/vwtask.py", line 7, in <module>
    from tasklib import Task
ImportError: No module named 'tasklib'
Traceback (most recent call last):
  File "$nvim/plugins/plugged/taskwiki/taskwiki/main.py", line 15, in <module>
    from taskwiki import cache as cache_module
  File "$nvim/plugins/plugged/taskwiki/taskwiki/cache.py", line 5, in <module>
    from taskwiki import viewport
  File "$nvim/plugins/plugged/taskwiki/taskwiki/viewport.py", line 6, in <module>
    from taskwiki import vwtask
  File "$nvim/plugins/plugged/taskwiki/taskwiki/vwtask.py", line 7, in <module>
    from tasklib import Task
ImportError: No module named 'tasklib'
Press ENTER or type command to continue
```

**Comment by swalladge** [comment]
This isn't a problem with taskwiki. Check your python environment. If you had to install with `sudo` and `-H`, something is wrong...

You should be able to run the same python3 executable that nvim uses (run `:checkhealth` to find it) and from within the repl `import tasklib` needs to work.

**Comment by tbabej** [comment]
You can also check by running `:py3 import tasklib` in the vim.

**Comment by vnd** [comment]
Had the same issue, fixed by
`pip3 install tasklib`

**Comment by nocibambi** [comment]
I had the same problem. I ran `:checkhealth` which showed that the `pynvim` module was not installed. Installing it made it work.

**Comment by mrbig033** [comment]
This is usse is for 2018. I stopped using this altogether. Thank you for the effort anyway. Sorry guys.
