### ISSUE TITLE
Missing tasks & dependency indentations when using non project viewports

### ISSUE THREAD

**Issue by arooni** [tbabej/taskwiki#188]
As always thanks for writing this amazing software.

My issue is as follows:  In order to decide what to do each day I move the tasks I want to accomplish to priority:H the previous night.  That way I wake up and know what's on the agenda each day.  

So my viewport for todays tasks looks like:

== Today's Tasks | priority:H +READY ==

So this generally works pretty well.  But I do seem to have the following issues:  
1) create a new task underneath this view port. call it 'parent task'  everything seems great; it gets the priority:H set correctly  
2) create a subtask for the new task, call it 'child task'  
3) when hitting save; the parent task is suddenly gone.  but the child task is listed, but unindented.  in the taskwarrior data store, the dependencies are all set correctly and both tasks exist when running a filter query of task... and that's great.  but i'd love to see the indentation and parent tasks listed in taskwiki.  i also tried quitting vim and restarting it without affect.  the parent task is still missing from taskwikis perspsective even though it exists in taskwarrior.  

i tested this with a viewport of 
== foo project | project:foo == 
and there was no problem!  so is it something weird about my viewport?  let me know!  thanks!

**Comment by arooni** [comment]
finally, if recreate the viewport 
== Today's Tasks | priority:H +READY ==
just for fun, it looks like it reproduces all tasks WITH THE EXCEPTION of any 'parent' tasks... i.e. any tasks that have dependencies.

**Comment by arooni** [comment]
was messing with my filter like using +PENDING instead of ready and ran into; 

**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/david/.vim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/david/.vim/plugged/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/david/.vim/plugged/taskwiki/taskwiki/main.py", line 62, in update_to_tw
    c.evaluate_viewports()
  File "/home/david/.vim/plugged/taskwiki/taskwiki/cache.py", line 238, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/david/.vim/plugged/taskwiki/taskwiki/viewport.py", line 381, in sync_with_taskwarrior
    sort.TaskSorter(self.cache, self.tasks, self.sort).execute()
  File "/home/david/.vim/plugged/taskwiki/taskwiki/sort.py", line 37, in execute
    child.parent = node
  File "/home/david/.vim/plugged/taskwiki/taskwiki/sort.py", line 154, in parent
    raise ValueError("TaskCollectionNode %s cannot have multiple parents" % repr(self))


maybe this was the issue

**Comment by arooni** [comment]
I also tried:

== Today's task HEADER [pri:H +PENDING +READY] || priority:H and +PENDING and +READY ==

and creating new tasks underneath it; but it appears that these new tasks do not inherit priority:H

**Comment by arooni** [comment]
well the first issue i opened with was due to my not designing filters correctly.  i need to include blocked tasks if I want to see the subtasks correctly

== Today's Task Viewport | priority:H (+READY or +BLOCKED)  ==

seems to fix it.

**Comment by arooni** [comment]
unrelated: anyway to 'collapse' viewports/filters?  i.e. hide tasks that fall underneath them?
