### ISSUE TITLE
taskwiki crash on startup

### ISSUE THREAD

**Issue by blastmaster** [tbabej/taskwiki#203]
Hi, I use `taskwiki` since a year or so and it works always fine but now I get the following error when loading my index page. 
```
"                                                                                                                                            
Error detected while processing /home/soeste/code/dofiles/vim/bundle/taskwiki/ftplugin/vimwiki/taskwiki.vim:                                                                                   
line   33:                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                             
  File "<string>", line 1, in <module>                                                                                                                                                         
  File "/home/soeste/code/dofiles/vim/bundle/taskwiki/taskwiki/main.py", line 15, in <module>                                                                                                  
    from taskwiki import cache as cache_module                                                                                                                                                 
  File "/home/soeste/code/dofiles/vim/bundle/taskwiki/taskwiki/cache.py", line 5, in <module>                                                                                                  
    from taskwiki import preset                                                                                                                                                                
  File "/home/soeste/code/dofiles/vim/bundle/taskwiki/taskwiki/preset.py", line 5, in <module>                                                                                                 
    from taskwiki import util                                                                                                                                                                  
  File "/home/soeste/code/dofiles/vim/bundle/taskwiki/taskwiki/util.py", line 6, in <module>                                                                                                   
    import pkg_resources                                                                                                                                                                       
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3126, in <module>                                                                                                      
    @_call_aside                                                                                                                                                                               
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3110, in _call_aside                                                                                                   
    f(*args, **kwargs)                                                                                                                                                                         
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set                                                                                
    for dist in working_set                                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3154, in <genexpr>                                                                                                     
    for dist in working_set                                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2661, in activate                                                                                                      
    declare_namespace(pkg)                                                                                                                                                                     
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2187, in declare_namespace                                                                                             
    _handle_ns(packageName, path_item)                                                                                                                                                         
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2104, in _handle_ns                                                                                                    
    loader = importer.find_module(packageName)                                                                                                                                                 
AttributeError: module 'vim' has no attribute 'find_module'                                                                                                                                    
Error detected while processing BufEnter Autocommands for "*.wiki":                                                                                                                            
Traceback (most recent call last):                                                                                                                                                             
  File "<string>", line 1, in <module>                                                                                                                                                         
NameError: name 'cache' is not defined     
```

This looks quite strange for me. Why does it try to call `find_modules` on the vim module? 
Since you ask for `tasklib` https://github.com/tbabej/taskwiki/blob/eaffcbd7185fc5c0dfec23821604527e4e8b0045/taskwiki/util.py#L374 here, which is the only use of `pkg_resources`.

Here is the output of `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 05 2019 20:53:12)
Included patches: 1-693
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              +mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-SsPCMM/vim-8.1.0693=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     
```

It's compiled with python3 support as usual and `vimwiki` and `taskwiki` are installed and up-to-date using `vim-plug`.
```
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }                                                                                                                                              
Plug 'tbabej/taskwiki'  
```

The `tasklib` library is installed with `pip3`.
```
{~} » pip3 show tasklib
Name: tasklib
Version: 1.1.0
Summary: Python Task Warrior library
Home-page: https://github.com/robgolding63/tasklib
Author: Rob Golding
Author-email: rob@robgolding.com
License: BSD
Location: /home/soeste/.local/lib/python3.7/site-packages
Requires: tzlocal, six, pytz
Required-by:
```

I hope you can help me figure out whats going wrong here.

**Comment by tbabej** [comment]
The setup looks ok, if this suddenly stopped working, I would look into downgrading vim. I suspect that's where the issue came from, as your version was built on Jan 9th 2019.

**Comment by beuerle** [comment]
Reported in #183. The patch reported by @bbugyi200 in https://github.com/tbabej/taskwiki/issues/183#issuecomment-411231260 works fine.

**Comment by blastmaster** [comment]
@beuerle you are right that is exactly the same error. I spent the weekend in the vim sources and the conclusion was the same as in #183, so this is at least not an taskwiki bug. But I'am still somehow confused if it is a bug in `setuptools` or in `vim`?

**Comment by blastmaster** [comment]
I close this issue, the bug is on the vim side and should be fixed with https://github.com/vim/vim/commit/b999ba2778b6c02fdd100e498a9ba5b2e7036f7d .

**Comment by tbabej** [comment]
Great to know, thanks @blastmaster !
