### ISSUE TITLE
Errors Kubuntu and WSL

### ISSUE THREAD

**Issue by abers** [tbabej/taskwiki#205]
I am experiencing errors with taskwiki on both Kubuntu and using the Windows Subsystem for Linux. I created a new vimwiki page with taskwiki viewport to show "project:work". On opening / saving the page I received the following error messages -

WSL:
```
Error detected while processing BufWrite Auto commands for "*.md":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/main.py", line 62, in update_to_tw
    c.evaluate_viewports()
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/cache.py", line 249, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/viewport.py", line 330, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/viewport.py", line 304, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/home/alasdair/.vim/bundle/taskwiki/taskwiki/viewport.py", line 282, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/usr/local/lib/python3.6/dist-packages/tasklib/task.py", line 485, in __iter__
    self._result_cache = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/tasklib/task.py", line 517, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/usr/local/lib/python3.6/dist-packages/tasklib/backends.py", line 324, in filter_tasks
    filtered_task._load_data(json.loads(data))
  File "/usr/local/lib/python3.6/dist-packages/tasklib/task.py", line 67, in _load_data
    self._original_data = copy.deepcopy(self._data)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.6/copy.py", line 273, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/home/alasdair/.local/lib/python3.6/site-packages/pytz/__init__.py", line 284, in _p
    return unpickler(*args)
  File "/home/alasdair/.local/lib/python3.6/site-packages/pytz/tzinfo.py", line 539, in unpickler
    tz = pytz.timezone(zone)
  File "/home/alasdair/.local/lib/python3.6/site-packages/pytz/__init__.py", line 178, in timezone
    raise UnknownTimeZoneError(zone)
```

... and on Kubuntu:
```
REMOVED
```

Edit: Figured out initial issue on Kubuntu was from having a task with multiple parents, then fixed the second issue by deleting the test page and creating a new one. Everything seems to be working fine on Kubuntu now.

**Comment by tbabej** [comment]
This looks like a timezone problem, located within tasklib. Can you check what timezone is detected using the `tzlocal` library on WSL?

**Comment by tbabej** [comment]
See usage: https://github.com/regebro/tzlocal

**Comment by abers** [comment]
Thanks for the reply. tzlocal.get_localzone() returns DstTzInfo 'local' STD0:00:00 STD. This 'local' timezone instead of reference to an actual timezone seems to be a known issue with the way the WSL is currently configured. See https://github.com/Microsoft/WSL/issues/3747

**Comment by abers** [comment]
It appears that the issue may be solved for those able to update to the latest version of Windows 10. However, I am on the work PC so unsure when IT will approve the relevant update on the network.

Found an alternative solution [here](https://code.medula.cl/article_karma-chrome-ubuntu-timezone.html).

```
sudo mv /etc/localtime /etc/no-localtime
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
```

The issue is that WSL sets /etc/localtime using a symbolic link to a file that grabs it from Windows but does not specify all the timezone information programs often assume exists on Linux - resulting in errors. So changing the link within the WSL to the relevant timezone from /usr/share/zoneinfo/... fixes any timezone related errors.

**Comment by tbabej** [comment]
Oh, if workaround is what you are searching for then it should be sufficient to explicitly set the `TZ` environment variable, see #110.

**Comment by xarthurx** [comment]
@abers Just found this plugin and Windows user here.

May I ask if you use vim inside WSL or outside?
Seeking possibilities to use taskwiki in vim outside WSL....

**Comment by abers** [comment]
Apologies for the delay in reply. I use vim inside WSL.
