### ISSUE TITLE
bug(?): TaskWikiProjects errors

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#21]
Love the idea, but seeing errors;

"~/.vim/wiki/index.wiki" 85L, 3849C
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/taskwiki.py", line 58, in projects
    util.show_in_split(output, name="projects", vertical=True)
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/util.py", line 117, in show_in_split
    vim.current.buffer.append(lines, 0)
TypeError: bad argument type for built-in operation

**Comment by tbabej** [comment]
Are you using the updated version of vim? Verify with ```vim --version```

**Comment by linuxcaffe** [comment]
pebkac :)
