### ISSUE TITLE
NvimError

### ISSUE THREAD

**Issue by tom-doerr** [tbabej/taskwiki#227]
I get the following error message 
```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/tom/.vim/bundle/taskwiki/taskwiki/main.py", line 277, in task_info_or_vimwiki_follow_link
    vim.command('VimwikiFollowLink')
  File "/home/tom/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/tom/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/tom/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(return):Traceback (most recent call last):'
Press ENTER or type command to continue
```
when trying to open this wiki file:
```
= Bachelorarbeit = 
== correct_deepspeech_prediction | +ba project:correct_deepspeech_prediction ==
```

Any idea what the issue could be? Other Viewports work without throwing errors.

**Comment by tom-doerr** [comment]
I solved it by deleting the following task:
```
➜  ~ t eb7181a9
No command specified - assuming 'information'.

Name                  Value
ID                    -
Description           inf what current error message
Status                Deleted
Project               correct_deepspeech_prediction
This task is blocking 244 test prediction on audio with many iterations
Entered               2019-08-18 19:14:26 (19h)
End                   2019-08-19 14:33:38
Last modified         2019-08-19 14:33:39 (1min)
Tags                  ba prof
Virtual tags          DELETED TAGGED UDA UNBLOCKED PROJECT
UUID                  eb7181a9-e0ae-443f-a1e4-53b1445af592
Urgency                3.7
Ti                    -

    project            1 *    1 =      1
    tags             0.9 *    1 =    0.9
    UDA priority.      1 *  1.8 =    1.8
                                  ------
                                     3.7

Date                Modification
2019-08-19 10:26:42 Start set to '2019-08-19 10:26:41'.
2019-08-19 10:26:43 Start deleted (duration: PT1S).
2019-08-19 10:27:02 Start set to '2019-08-19 10:27:01'.
2019-08-19 10:27:04 Start deleted (duration: PT2S).
2019-08-19 10:27:19 Start set to '2019-08-19 10:27:18'.
2019-08-19 10:27:20 Start deleted (duration: PT1S).
2019-08-19 10:30:53 Dependencies set to '0'.
2019-08-19 10:31:04 Dependencies '0' deleted.
2019-08-19 10:31:05 Dependencies set to '0'.
2019-08-19 14:16:39 Dependencies '0' deleted.
2019-08-19 14:16:40 Dependencies set to '0'.
2019-08-19 14:16:53 Dependencies '0' deleted.
2019-08-19 14:16:53 Dependencies set to '0'.
2019-08-19 14:16:56 Dependencies '0' deleted.
2019-08-19 14:16:56 Dependencies set to '0, 0'.
2019-08-19 14:17:02 Dependencies changed from '0, 0' to '0'.
2019-08-19 14:17:07 Dependencies changed from '0' to '0, 0'.
2019-08-19 14:17:08 Dependencies changed from '0, 0' to '0'.
2019-08-19 14:18:03 Dependencies '0' deleted.
2019-08-19 14:18:04 Dependencies set to '0'.
2019-08-19 14:18:06 Dependencies '0' deleted.
2019-08-19 14:18:06 Dependencies set to '0'.
2019-08-19 14:18:32 Dependencies '0' deleted.
2019-08-19 14:18:36 Dependencies set to '0'.
2019-08-19 14:18:43 Dependencies changed from '0' to '0, 0'.
2019-08-19 14:18:44 Dependencies changed from '0, 0' to '0, 0, 0'.
2019-08-19 14:18:47 Dependencies changed from '0, 0, 0' to '0, 0, 0, 0'.
2019-08-19 14:33:39 End set to '2019-08-19 14:33:38'.
                    Status changed from 'pending' to 'deleted'.

```

**Comment by tbabej** [comment]
Those dependencies set to 0, especially mutliple times, look weird.

**Comment by tom-doerr** [comment]
Probably caused by the Plugin 'vim-autoread', as described in #228.
