### ISSUE TITLE
Filter project.not results in error

### ISSUE THREAD

**Issue by MultiCoreNop** [tbabej/taskwiki#231]
The following does work as expected:
`== My Stuff | project:stuff and project.not:stuff.filthy ==`

This results in an error:
`== My Stuff | project.not:stuff.filthy ==`

Error:
```
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/user/.vim/bundle/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/user/.vim/bundle/taskwiki/taskwiki/main.py", line 62, in update_to_tw
    c.evaluate_viewports()
  File "/home/user/.vim/bundle/taskwiki/taskwiki/cache.py", line 249, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/user/.vim/bundle/taskwiki/taskwiki/viewport.py", line 381, in sync_with_taskwarrior
    sort.TaskSorter(self.cache, self.tasks, self.sort).execute()
  File "/home/user/.vim/bundle/taskwiki/taskwiki/sort.py", line 37, in execute
    child.parent = node
  File "/home/user/.vim/bundle/taskwiki/taskwiki/sort.py", line 154, in parent
    raise ValueError("TaskCollectionNode %s cannot have multiple parents" % repr(self))  
```

**Comment by sozforex** [comment]
Make sure that you have no tasks that block multiple other tasks.
You will get this error when taskwiki tries to create and display tree hierarchy containing three tasks, two of which depend on the third one (two parents for one task).

**Comment by MultiCoreNop** [comment]
I do not see any, but if this also applies to completed tasks, it might well be there were some blocking multiple tasks.

**Comment by cgardner** [comment]
If you have this problem with completed tasks and don't want them to show on the list, I added `+READY` to filter out the closed tasks
