### ISSUE TITLE
Error with neovim

### ISSUE THREAD

**Issue by juaneduardoflores** [tbabej/taskwiki#254]
Hello! I have been having trouble getting taskwiki to work in neovim. After scratching my head for a while I tried it in regular vim and it seemed to work fine. However in nvim taskwiki removes the syntax highlighting for wiki files that was there with vimwiki alone, and gives me some python errors. 
It appears to not be able to find a module called six, but I am confused about why it works in regular vim with the exact vimrc file. Also the help file is accessible but no commands are found. It doesn't seem to be using the file that is in the ftplugin directory.

I am using vim-plug to install
My vimrc looks like this:

call plug#begin('~/.config/nvim/plugged')
Plug 'vimwiki/vimwiki', {'branch': 'dev'}
Plug 'tbabej/taskwiki'
call plug#end()

I am using taskwarrior version 2.5.1
tasklib-2.1.1
NVIM v0.4.3

**When I install the plugins for the first time and go to index.wiki file I get this:**

```
Error detected while processing function provider#python3#Call:                                                                                                   
line   18:
Error invoking 'python_execute_file' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "~/.config/nvim/plugged/taskwiki/taskwiki/main.py", line 6, in <module>
    import six
ModuleNotFoundError: No module named 'six'

Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cache' is not defined
```

**And when I went into a link to a file and go back I got this:**

```
Error detected while processing function provider#python3#Call:                                                                                                  
line   18:
Error invoking 'python_execute_file' on channel 3 (python3-script-host):^@Traceback (most recent call last):^@  File "~/.config/nvim/plugged/taskwik
i/taskwiki/main.py", line 6, in <module>^@    import six^@ModuleNotFoundError: No module named 'six'
Error detected while processing function vimwiki#base#go_back_link:
line   12:
E171: Missing :endif
```

**Comment by juaneduardoflores** [comment]
I am fairly new to vim with minimal experience in python so forgive me for my silliness. I checked and the six module is installed for python2 but not 3. After installing the module in python3 and removing and re-installing the plugins it seems to be working fine now. Not sure why the module wasn't installed to begin with but I guess if anyone is new and has this issue maybe this could help them.
