### ISSUE TITLE
Taskwiki not working with taskwarrior 2.6.0

### ISSUE THREAD

**Issue by ulrichschinz** [tbabej/taskwiki#369]
Today an upgrade for task was available, which I installed.

Taskwiki will not work with task 2.6.0 (installed in arch linux), I cannot "<leader>t <action>" anymore (like edit task with ",te" or set task to done with ",td". Also filters do not work anymore.

Errormessage for <leader>t<action> is looking like this:

```
Command used: task rc.confirmation=no rc.dependency.confirmation=no rc.recurrence.confirmation=no rc.json.array=off rc.bulk=0 rc.context= export 37da4de4
Error detected while processing function provider#python3#Call:----------------------------------------------------------------------------------------------------
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/main.py", line 79, in __init__
    self.tw = cache().get_relevant_tw()
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/cache.py", line 311, in get_relevant_tw
    task = vwtask.VimwikiTask.find_closest(self)
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/vwtask.py", line 67, in find_closest
    vwtask = cls.from_line(cache, i)
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/vwtask.py", line 107, in from_line
    self.task['description'] = match.group('text')
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/vwtask.py", line 211, in task
    return self.cache.task[self.uuid]
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/store.py", line 58, in __getitem__
    item = self.get_method(key)
  File "/home/myusername/.dotfiles/nvim/plugged/taskwiki/taskwiki/store.py", line 107, in get_method
    return key.tw.tasks.get(uuid=key.value)
  File "/home/myusername/.local/lib/python3.9/site-packages/tasklib/task.py", line 548, in get
    num = len(clone)
  File "/home/myusername/.local/lib/python3.9/site-packages/tasklib/task.py", line 471, in __len__
    self._result_cache = list(self.__iter__())
  File "/home/myusername/.local/lib/python3.9/site-packages/tasklib/task.py", line 476, in __iter__
    self._result_cache = self._execute()
  File "/home/myusername/.local/lib/python3.9/site-packages/tasklib/task.py", line 508, in _execute
    return self.backend.filter_tasks(self.filter_obj)
  File "/home/myusername/.local/lib/python3.9/site-packages/tasklib/backends.py", line 334, in filter_tasks
    for line in self.execute_command(args):
  File "/home/myusername/.local/lib/python3.9/site-packages/tasklib/backends.py", line 297, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: TASKRC override: /home/myusername/.taskrc
Configuration override rc.confirmation=no
Configuration override rc.dependency.confirmation=no
Configuration override rc.recurrence.confirmation=no
Configuration override rc.json.array=off                                                                                                                                                                           
Configuration override rc.bulk=0                                                                                                                                                                                   
Configuration override rc.context=                                                                                                                                                                                 
Unable to find report that matches '37da4de4'.                                                                                                                                                                     
Command used: task rc.confirmation=no rc.dependency.confirmation=no rc.recurrence.confirmation=no rc.json.array=off rc.bulk=0 rc.context= export 37da4de4
```

Infos on versions:

Taskwarrior
```
) task --version                                                                                                                                                            
2.6.0
```

Neovim
```
:version                                                                                                                                                           
NVIM v0.5.1
Build type: Release
```

pynvim
```
) yay -Ss pynvim
community/python-pynvim 0.4.3-1 (64.4 KiB 319.3 KiB) (Installed)
    Python client for Neovim
```
tasklib has been installed from dev-branch.

Upgraded all Plugins with "nvim +PlugUpdate"

EDIT:
By the way:
Downgrading taskwarrior to 2.5.3 makes everything shiny again... But still would be nice to have task 2.6.0 working...

**Comment by tbabej** [comment]
I believe this error was pre-emptively fixed before the `2.6.0` release, but you'll have to update your `tasklib` version to the [newest `2.4.0`](https://github.com/GothenburgBitFactory/tasklib/releases/tag/2.4.0) via `pip install -U tasklib` :slightly_smiling_face:

**Comment by ulrichschinz** [comment]
@tbabej  Thanks for that... Thought installing from git develop branch would have fixed it, but seems, that I didn't get it the right way...
`pip install -U tasklib`  fixed it!
Thank you again !

**Comment by juanedflores** [comment]
I am getting the same error with this environment:

Taskwarrior
```
task --version
2.6.1
```

Neovim
```                                                            
NVIM v0.7.0-dev+797-gb218d02c4  
```

pynvim
```                                                            
0.4.3
```

tasklib
```                                                            
2.4.3
```

**Comment by tbabej** [comment]
@juanedflores Most likely explanation would be that the `tasklib` version 2.4.3 is installed in a different location (i.e. using a different Python version) than what neovim uses in your case. I'd recommend trying to get the version using `:py3` commands inside the vim session.

**Comment by juanedflores** [comment]
@tbabej I wasn't expecting an answer that fast. Turns out you were totally right! I have installed in the proper place now.

**Comment by tbabej** [comment]
@juanedflores No worries, happy to help!

**Comment by huntse** [comment]
I had what looked like the same issue even though I have version 2.4.3 reported by `:py3 import tasklib;print(tasklib.__version__)` in neovim and a clean bill of health via `:checkhealth`.  My neovim python virtualenv predated me upgrading task.

The thing which fixed it in the end was nuking the virtualenv and making a new one.  Now it works.
