### ISSUE TITLE
bug: TaskWikiAnnotate crash

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#45]
to reproduce, cursor over a task, invole :TaskWikiAnnotate, but don't enter a value, hit ESC instead.

I get;
<pre>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/taskwiki.py", line 96, in annotate
    vimwikitask.task.add_annotation(annotation)
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 666, in add_annotation
    self.warrior.execute_command(args)
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 947, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.task.TaskWarriorException: Using alternate .taskrc file /
Using alternate data.location /home/djp/.task
Configuration override rc.bulk:0
Configuration override rc.confirmation:no
Configuration override rc.data.location:/home/djp/.task
Configuration override rc.context:
Configuration override rc.recurrence.confirmation:no
Configuration override rc.dependency.confirmation:no
Additional text must be provided.
</pre>

**Comment by tbabej** [comment]
Fixed in master.
