### ISSUE TITLE
ViewPort errors

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#67]
when trying to update the filter in a viewport with
<pre>
== Calls to Make | +PENDING (desc.startswith:call or +call) need < 3 == 
</pre>
 I get these errors:
<pre>
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/taskwiki.py", line 54, in update_to_tw
    cache.evaluate_viewports()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/cache.py", line 205, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/viewport.py", line 144, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/viewport.py", line 118, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/viewport.py", line 96, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 833, in __iter__
    self._result_cache = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 865, in _execute
    return self.warrior.filter_tasks(self.filter_obj)
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 1004, in filter_tasks
    for line in self.execute_command(args):
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 982, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.task.TaskWarriorException: Using alternate .taskrc file /home/djp/.taskrc
Using alternate data.location /home/djp/.task
Configuration override rc.bulk:0
Configuration override rc.confirmation:no
Configuration override rc.data.location:/home/djp/.task
Configuration override rc.context:
Configuration override rc.recurrence.confirmation:no
Configuration override rc.dependency.confirmation:no
"~/.vim/wiki/diary/2015-05-07.wiki" 72L, 2705C written
Press ENTER or type command to continue
</pre>
I've tried variations of the syntax, without success, and it seems to be related to the use of a uda.

**Comment by linuxcaffe** [comment]
on reopening the offending (vimwiki diary) file, I see this flash past;
<pre>
Error detected while processing /home/djp/.vim/bundle/taskwiki/ftplugin/vimwiki.vim:
line   15:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/taskwiki.py", line 500, in <module>
    WholeBuffer.update_from_tw()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/taskwiki.py", line 41, in update_from_tw
    cache.evaluate_viewports()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/cache.py", line 205, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/viewport.py", line 144, in sync_with_taskwarrior
    to_add, to_del = self.get_tasks_to_add_and_del()
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/viewport.py", line 118, in get_tasks_to_add_and_del
    matching_tasks = self.matching_tasks
  File "/home/djp/.vim/bundle/taskwiki/taskwiki/viewport.py", line 96, in matching_tasks
    task for task in self.tw.tasks.filter(*args)
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 833, in __iter__
    self._result_cache = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 865, in _execute
    return self.warrior.filter_tasks(self.filter_obj)
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 1004, in filter_tasks
    for line in self.execute_command(args):
  File "/usr/local/lib/python2.7/dist-packages/tasklib-0.9.0-py2.7.egg/tasklib/task.py", line 982, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.task.TaskWarriorException: Using alternate .taskrc file /home/djp/.taskrc
Using alternate data.location /home/djp/.task
Configuration override rc.bulk:0
Configuration override rc.confirmation:no
Configuration override rc.data.location:/home/djp/.task
Configuration override rc.context:
Configuration override rc.recurrence.confirmation:no
Configuration override rc.dependency.confirmation:no
Unmatched ( or \(
Tagbar: Could not execute ctags for /home/djp/.vim/wiki/diary/2015-05-07.wiki!
Executed command: "'i~/bin/vwtags.py'  default  '/tmp/vVvft6A/7.wiki'"
Command output:
/bin/bash: i~/bin/vwtags.py: No such file or directory
Press ENTER or type command to continue
</pre>

**Comment by tbabej** [comment]
Can you verify if these still apply?

**Comment by linuxcaffe** [comment]
these do not apply, everything working smoothly
