### ISSUE TITLE
dependency to tasklib

### ISSUE THREAD

**Issue by kraxli** [tbabej/taskwiki#86]
Hi 

I am working on Windows7 with vim74-898, python 2.7.10, and taskwarrior 2.4.4 . I followed your installation istructions. Opening a wiki-file in vim produces the following error:  

```
"U:/vimwiki/index.wiki" [unix] 69L, 1445C
Error detected while processing C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki/ftplugin/vimwiki.vim:
line   27:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki/taskwiki/taskwiki.py", line 8, in <module>
    from tasklib import TaskWarrior
ImportError: cannot import name TaskWarrior
```

Ok I change the import statement in the taskwiki.py to 

```
from tasklib.task import TaskWarrior
```

Now I get the error:

```
Error detected while processing C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki/ftplugin/vimwiki.vim:
line   27:
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki/taskwiki/taskwiki.py", line 16, in output_exception
    if exception_type is util.TaskWikiException:
NameError: global name 'util' is not defined
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki/taskwiki/taskwiki.py", line 23, in <module>
    import cache
  File "C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki\taskwiki\cache.py", line 5, in <module>
    import vwtask
  File "C:/Prgm/Vim/vim74898/vimfiles/bundle/taskwiki\taskwiki\vwtask.py", line 6, in <module>
    from tasklib import Task
ImportError: cannot import name Task
```

Any clue what I am doing wrong?

Thx

**Comment by tbabej** [comment]
You have an old version of tasklib installed. The instructions say that you have to install the development branch, I bet you have installed from 'master' branch, not 'develop'.

**Comment by kraxli** [comment]
indeed I just realized that the update to tasklib@dev did not work and I still had tasklib@master in. Now it works :-) 
Thanks!
