### ISSUE TITLE
Hard lock on startup

### ISSUE THREAD

**Issue by csaintc** [tbabej/taskwiki#94]
hey guys, I'm currently getting a hard-lock when I try to open the taskwiki files.

Version info:

```
10001 ◯  task --version
2.5.0
```

```
vim --version
NVIM 0.1.2-dev
```

```
10007 ◯  pip show tasklib
---
Name: tasklib
Version: 0.11.0
```

A path forward ( how to access the stack trace, etc. ) would be helpful.

Thanks!

**Comment by tbabej** [comment]
Hi,

can you please make sure that you have taskwiki on HEAD? Last three commits pushed are for Neovim compatibility. I believe I already encountered & fixed this, but I may be wrong.

**Comment by tbabej** [comment]
Also, you may need to update the tasklib install, as stated in the README:

    sudo pip install --upgrade git+git://github.com/tbabej/tasklib@develop

**Comment by csaintc** [comment]
Ahh, there we go, now i'm getting stack traces:

```
Error detected while processing function provider#python#Call:                                                                                                                                                                                 
line   18:                                                                                                                                                                                                                                     
NvimError('Index out of bounds',)                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 177, in handler                                                                                                                                            
    rv = self._request_cb(name, args)                                                                                                                                                                                                          
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 237, in filter_request_cb                                                                                                                                           
    walk(self._in, args, self, name, 'request'))                                                                                                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/neovim/plugin/host.py", line 65, in _on_request                                                                                                                                                 
    rv = handler(*args)                                                                                                                                                                                                                        
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute                                                                                                                                                  
    exec(script, self.module.__dict__)                                                                                                                                                                                                         
  File "<string>", line 1, in <module>                                                                                                                                                                                                         
NvimError: Index out of bounds 
```

and I've also gotten the error: `Feed the dog matches multiple tasks` a few times, but I'm unable to reproduce it at this time.

**Comment by tbabej** [comment]
You can see that the stack trace gets a bit truncated (this is an unfortunate vim behaviour) by default, can you run

    :messages

to show the full trace?

Also, is taskwiki itself on HEAD? The very last commit should fix an out of bounds issue for windows in Neovim.

**Comment by csaintc** [comment]
Yeah, I'm on HEAD

Additionally, I'm on Ubuntu 14.04, not windows:

```
Error detected while processing function provider#python#Call:                                                                                                                
line   18:                                                                                                                                                                    
NvimError('Index out of bounds',)                                                                                                                                             
Traceback (most recent call last):                                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 177, in handler                                                                           
    rv = self._request_cb(name, args)                                                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 237, in filter_request_cb                                                                          
    walk(self._in, args, self, name, 'request'))                                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/neovim/plugin/host.py", line 65, in _on_request                                                                                
    rv = handler(*args)                                                                                                                                                       
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute                                                                                 
    exec(script, self.module.__dict__)                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                        
NvimError: Index out of bounds    
```

**Comment by tbabej** [comment]
I don't think this is distro-related, I'm on Fedora 23. The thing is, I can't reproduce so far, taskwiki is running in neovim for me.

    NVIM 0.1.1 (compiled Dec  9 2015 13:03:38)    

Maybe you can try updating the python-neovim package?

    https://github.com/neovim/python-client

Other than that, you'd need to identify which object access fails with Index out of bounds error.

**Comment by csaintc** [comment]
Could it be that I'm in taskwarrior 2.5?

**Comment by tbabej** [comment]
No, taskwiki is fully compatible with TW 2.5.0.

**Comment by csaintc** [comment]
python client up to date already, as well

**Comment by tbabej** [comment]
@csaintc I'm sorry, it seems that I had the Neovim compatibility patches applied only locally, and not pushed yet. Try to update taskwiki (I just pushed them) and see if the issue still persists.

**Comment by csaintc** [comment]
Nice, that did it. i was still able to see the 'matches multiple tasks' error, but it seems to work now. Thanks for the help!

**Comment by csaintc** [comment]
Also:
```
Error detected while processing function provider#python#Call:                                                                                     
line   18:                                                                                                                                         
NvimError('Vim(edit):E325: ATTENTION',)                                                                                                            
Traceback (most recent call last):                                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 177, in handler                                                
    rv = self._request_cb(name, args)                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 237, in filter_request_cb                                               
    walk(self._in, args, self, name, 'request'))                                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/neovim/plugin/host.py", line 65, in _on_request                                                     
    rv = handler(*args)                                                                                                                            
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute                                                      
    exec(script, self.module.__dict__)                                                                                                             
  File "<string>", line 1, in <module>                                                                                                             
NvimError: Vim(edit):E325: ATTENTION 
```

( Hopefully I'm not coming off as disgruntled, I'm just trying to be helpful because I think this is a cool project! :) )

**Comment by tbabej** [comment]
When did the last error happen?

**Comment by csaintc** [comment]
Just after I pulled your latest changes

**Comment by tbabej** [comment]
Yes, but was there any trigger? Does it happen immediately after opening a taskwiki file, that is, at startup?

**Comment by csaintc** [comment]
It happened after I opened a file with this task block:

```
== TASKS ==
* [ ] Write TextHighlightQuestionResponseStats stuff
* [ ] Fix text highlighting on actual question
* [ ] Get rid of dupe code between TextHighlight and TextHighlightEditor
  - [ ] Put them in a central utility function file
* [ ] Work with DC in order to get everything all styled and pretty
* [ ] Get facebook flow working nice
* [ ] Clear out TODOs
```

**Comment by csaintc** [comment]
Looks like a validation thing: I hadn't tried to set this block up to be managed by TaskWiki yet, but after I port it over it works great

**Comment by tbabej** [comment]
I don't think the error is there, I can't reproduce with a simple:

    ==== Test ====
    * [ ] test one
       - [ ] test sub
    * [ ] test two

**Comment by tbabej** [comment]
Oh, I overlooked the E325 error code. The E325 means the presence of the swap file, see:

http://superuser.com/questions/218262/how-to-get-rid-of-the-warnings-when-opening-a-file-that-has-a-swp-file

**Comment by tbabej** [comment]
Nevertheless, the underlying freeze issue is fixed, so let's continue in a new thread if necessary.
