### ISSUE TITLE
taskwiki errors

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#99]
on launching *.wiki files, I've been seeing these errors;

`"~/.task/wiki/index.wiki" 45L, 1987C
Error detected while processing /home/djp/dotfiles/vim/bundle/taskwiki/ftplugin/vimwiki.vim:
line   27:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/main.py", line 13, in <module>
    from taskwiki import cache
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/cache.py", line 4, in <module>
    from taskwiki import viewport
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/viewport.py", line 6, in <module>
    from taskwiki import vwtask
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/vwtask.py", line 6, in <module>
    from tasklib import Task
ImportError: cannot import name Task
Press ENTER or type command to continue
` 

and I'm not sure if it's actually a taskwiki thing, or something in my configuration.

**Comment by linuxcaffe** [comment]
oh wait, I've forgotten to keep up with tasklib..

**Comment by linuxcaffe** [comment]
yeah, that was it.

**Comment by linuxcaffe** [comment]
perhaps tasklib instructions should recommend "sudo python setup.py install" before the pip way?
